#FIX THIS
---
- name: Deploy File Receivers
  hosts: file_receivers

  vars:
    app_path: "/home/ubuntu/app"

  tasks:
    - name: Copy project files
      ansible.builtin.copy:
        src: ../FileReceiver/
        dest: "{{ app_path }}"

    - name: Install dependencies in virtual environment
      ansible.builtin.command: "/home/ubuntu/app/venv/bin/pip install -r /home/ubuntu/app/requirements.txt"
      changed_when: false

    - name: Copy systemd service file on the remote host
      ansible.builtin.command: cp /home/ubuntu/app/file_receiver.service /etc/systemd/system/file_receiver.service
      become: true
      changed_when: false


    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
      become: true

    - name: Enable and start service
      ansible.builtin.systemd:
        name: file_receiver
        enabled: true
        state: restarted
      become: true
