---
- name: Configure zookeepers
  hosts: zookeepers

  tasks:
    - name: Install Java (OpenJDK 11 - a common choice)
      ansible.builtin.package:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

  roles:
    - sleighzy.zookeeper
  vars:
    zookeeper_servers: "{{ groups['zookeepers'] }}"
