---
- name: Setup Ubuntu Linux Hosts
  hosts: all
  become: false

  vars:
    app_path: "{{ ansible_user_dir }}/app/"
    generated_hosts_file_source: "./generated_hosts.txt" 
    etc_hosts_destination: "/etc/hosts"

  tasks:
    - name: Install tzdata package
      ansible.builtin.apt:
        name: tzdata
        state: present
      become: true

    - name: Set timezone Europe/Bucharest
      community.general.timezone:
        name: Europe/Bucharest
      become: true

    - name: Add deadsnakes PPA for newer Python versions
      ansible.builtin.apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
        update_cache: true
      become: true

    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true 
      become: true

    - name: Upgrade all installed packages
      ansible.builtin.apt:
        upgrade: dist 
        autoremove: true 
        force_apt_get: true
      register: apt_upgrade_result
      become: true

    - name: Remove existing project files
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/app"
        state: absent
      become: true

    - name: Install Python 3.12 venv and pip
      ansible.builtin.apt:
        name:
          - python3.12 
          - python3.12-venv
          - python3.12-dev
        state: present
        force_apt_get: true
      become: true



    - name: Remove faulty
      ansible.builtin.apt:
        name: python3-pip 
        state: absent
      become: true

    - name: Create Python 3.12 virtual environment
      ansible.builtin.command: python3.12 -m venv {{ app_path }}venv
      args:
        creates: "{{ app_path }}venv/bin/activate"
      register: venv_creation_result
      changed_when: venv_creation_result.rc == 0

    - name: Upgrade pip within the virtual environment
      ansible.builtin.command: "{{ app_path }}/venv/bin/pip install --upgrade pip"
      register: pip_upgrade_result
      changed_when: "'Successfully installed pip' not in pip_upgrade_result.stdout"

    - name: Install dependencies
      ansible.builtin.command: "{{ app_path }}/venv/bin/pip install six packaging"

    - name: Display virtual environment path
      ansible.builtin.debug:
        msg: "Virtual environment created at: {{ app_path }}venv"

    - name: Copy generated_hosts.txt to /etc/hosts on remote machines
      ansible.builtin.copy:
        src: "{{ generated_hosts_file_source }}"
        dest: "{{ etc_hosts_destination }}"
        owner: root
        group: root
        mode: "0644"
      become: true
