---
- name: Setup PostgreSQL
  hosts: postgres
  become: true

  vars:
    postgresql_version: "14" 

  tasks:
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present
        update_cache: true

    - name: Check if PostgreSQL cluster 'main' exists
      ansible.builtin.command: "sudo -u postgres /usr/bin/pg_lsclusters"
      register: pg_clusters
      changed_when: false

    - name: Enable and start PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        enabled: true
        state: started
