- hosts: kafka
  become: true
  tasks:
    - name: Fetch the Kafka server.properties file
      ansible.builtin.fetch:
        src: /etc/kafka/server.properties # Adjust this path if necessary
        dest: /tmp/kafka_server.properties # Local path on your control node to save the file
        flat: yes
