- hosts: kafka
  become: true
  tasks:
    - name: Fetch the Kafka server.properties file
      ansible.builtin.fetch:
        src: /etc/kafka/server.properties
        dest: /tmp/kafka_server.properties
        flat: yes
